{
    "name": "PremaFirm AI Engine",
    "version": "18.0.6.7.0",
    "summary": "CRM Outreach, Snov.io Contacts, Geotab ELD, Invoicing for PremaFirm Logistics",
    "author": "PremaFirm",
    "license": "LGPL-3",
    "depends": [
        "crm",
        "crm_iap_enrich",
        "partner_autocomplete",
        "sale_management",
        "account",
        "mail",
        "fleet",
        "hr",
        "hr_attendance",
        "calendar",
        "base_setup",
        "documents",
        "mail_bot",
        "whatsapp",
        "prema_ai_auditor",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/business_profile_data.xml",
        "data/ml_cron.xml",
        "data/ml_crons.xml",
        "data/documents_ml_data.xml",
        "data/kc_ingest_cron.xml",
        "data/driver_tag_data.xml",
        "data/kc_data.xml",
        "data/email_segment_config.xml",
        "data/geotab_cron.xml",
        "data/pod_sync_cron.xml",
        "data/crm_bulk_email_cron.xml",
        "data/crm_stages.xml",
        "data/crm_followup_cron.xml",
        "data/crm_workflow_automations.xml",
        "views/ml_knowledge_views.xml",
        "views/ml_draft_views.xml",
        "views/ml_ingestion_views.xml",
        "views/ifta_fuel_log_views.xml",
        "views/crm_lead_ml_views.xml",
        "views/account_move_view.xml",
        "views/account_move_ml_views.xml",
        "views/sale_order_ml_views.xml",
        "views/documents_ml_views.xml",
        "views/crm_bulk_email_views.xml",
        "views/crm_view.xml",
        "views/sale_order_view.xml",
        "views/rate_estimator_view.xml",
        "views/ai_review_wizard_views.xml",
        "views/dispatch_wizard_view.xml",
        "views/invoice_ai_product_view.xml",
        "views/report_premafirm_pod.xml",
        "views/report_company_header_inherit.xml",
        "views/fleet_geotab_link_wizard_view.xml",
        "views/contact_geotab_link_wizard_view.xml",
        "views/fleet_vehicle_geotab_view.xml",
        "views/fleet_odometer_view.xml",
        "views/res_partner_driver_view.xml",
        "views/geotab_settings_view.xml",
        "views/bill_scan_import_views.xml",
        "views/res_partner_address_view.xml",
        "views/business_profile_views.xml",
        "views/crm_bulk_assign_views.xml",
        "views/crm_ai_assistant_views.xml",
        "views/crm_ai_reply_wizard_views.xml",
        "views/ml_menu.xml",
        "views/portal_quote_sign.xml",
        "views/sale_order_approval_tab.xml",
        "data/attendance_summary_cron.xml",
        "views/attendance_summary_views.xml",
        "views/staff_coaching_views.xml",
        "views/inbound_queue_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "premafirm_ai_engine/static/src/css/crm_kanban.css",
            "premafirm_ai_engine/static/src/css/estimator_chat_panel.css",
            "premafirm_ai_engine/static/src/xml/google_address_widget.xml",
            "premafirm_ai_engine/static/src/xml/estimator_chat_panel.xml",
            "premafirm_ai_engine/static/src/js/google_places_utils.js",
            "premafirm_ai_engine/static/src/js/google_address_widget.js",
            "premafirm_ai_engine/static/src/js/google_company_widget.js",
            "premafirm_ai_engine/static/src/js/google_partner_m2o.js",
            "premafirm_ai_engine/static/src/js/estimator_chat_panel.js",
            "premafirm_ai_engine/static/src/css/app_search.css",
            "premafirm_ai_engine/static/src/js/app_search.js",
        ],
    },
    "installable": True,
    "application": False,
    "controllers": ["controllers"],
}
