{
    "name": "Prema AI Auditor",
    "version": "18.0.1.0",
    "depends": [
        "account",
        "account_accountant",
        "fleet",
        "crm",
        "sale",
        "purchase",
        "documents",
        "mail",
        "web",
        "bus",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/default_rules.xml",
        "data/cron.xml",
        "views/chat_action.xml",
        "views/dashboard_action.xml",
        "views/cleanup_plan_action.xml",
        "views/audit_log_action.xml",
        "views/monitoring_dashboard.xml",
        "views/cleanup_views.xml",
        "views/ai_chat_views.xml",
        "views/audit_dashboard_views.xml",
        "views/audit_log_views.xml",
        "views/proposal_views.xml",
        "views/config_audit_views.xml",
        "views/schema_viewer_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "prema_ai_auditor/static/src/js/ai_chat.js",
            "prema_ai_auditor/static/src/components/ai_chat_upload/ai_chat_upload.js",
            "prema_ai_auditor/static/src/xml/chat_templates.xml",
            "prema_ai_auditor/static/src/components/ai_chat_upload/ai_chat_upload.xml",
            "prema_ai_auditor/static/src/scss/ai_upload.scss",
        ]
    },
    "application": True,
    "installable": True,
    "license": "OEEL-1",
}
