import json

from odoo import models


class CleanupPlanGenerator(models.AbstractModel):
    _name = "prema.plan.generator"
    _description = "Cleanup Plan Generator"

    def generate_plan(self):
        logs = self.env["prema.audit.log"].search([("status", "=", "open")])

        structured_logs = [
            {
                "model": log.model_name,
                "record_id": log.record_id,
                "severity": log.severity,
                "issue": log.explanation,
            }
            for log in logs
        ]

        response = self.env["prema.openai.client"].call(
            {
                "model": "gpt-4.1",
                "messages": [
                    {
                        "role": "system",
                        "content": "Generate structured staged cleanup plan JSON.",
                    },
                    {"role": "user", "content": json.dumps(structured_logs)},
                ],
            }
        )

        plan_json = json.loads(response["choices"][0]["message"]["content"])

        plan = self.env["prema.cleanup.plan"].create(
            {
                "name": "AI Generated Cleanup Plan",
                "summary": "Auto generated by GPT-4.1",
                "risk_score": self.env["prema.risk.matrix"].calculate_risk_score(),
            }
        )

        seq = 1
        for step in plan_json.get("steps", []):
            self.env["prema.cleanup.step"].create(
                {
                    "plan_id": plan.id,
                    "sequence": seq,
                    "action_type": step["action"],
                    "model_name": step["model"],
                    "record_id": step["record_id"],
                    "description": step["description"],
                    "severity": step["severity"],
                    "approval_stage": step["stage"],
                }
            )
            seq += 1

        return plan.id
