{
    "name": "PremaFirm AI Engine",
    "version": "1.4",
    "summary": "AI Pricing + Routing Engine for PremaFirm Logistics",
    "author": "PremaFirm",
    "license": "LGPL-3",
    "depends": [
        "crm",
        "sale_management",
        "account",
        "mail",
        "fleet",
        "hr",
        "calendar",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/product_data.xml",
        "views/crm_view.xml",
        "views/sale_order_view.xml",
        "views/account_move_view.xml",
        "views/report_premafirm_pod.xml",
    ],
    "installable": True,
    "application": False,
}
