# -*- coding: utf-8 -*-
"""AI Generate correction/feedback memory (SHARED by quotation and invoice AI).

Pipeline (both flows):
    AI Generate populates a record  →  a baseline snapshot is saved
    (premafirm.ai.baseline) listing exactly what AI wrote  →  when a HUMAN
    later edits one of those values through the web UI, the difference is
    detected and stored as premafirm.ai.feedback  →  future AI Generate calls
    retrieve the most relevant corrections (same customer first) and pass them
    to the model as context.

Guards (so only genuine human corrections are learned):
    * writes made by the AI flow itself run with context ai_apply_flow=True
      and are never learned;
    * writes outside an interactive HTTP user session (crons, scripts,
      shell/XML-RPC, public/portal users) are never learned;
    * only fields whose current value still equals the latest AI baseline
      ("AI-owned") are diffed — a field the user already changed is owned by
      the user and further edits to it are not re-learned as corrections;
    * a write that puts the value back to the product's own default name
      (user re-picked the product) is not a correction;
    * identical correction pairs are de-duplicated (hash unique constraint)
      — a repeat increments occurrence_count instead of creating a new row.

Scope: corrections are recorded at customer level by default (customer_id);
admin can change scope/type afterwards. Retrieval is strict: only the
calling customer's OWN corrections and GLOBAL (customer_id empty) rows are
ever returned — one customer's corrections can never leak into another
customer's prompt.
"""
import json
import logging
import re
from difflib import SequenceMatcher
from hashlib import md5

from odoo import api, fields, models

_logger = logging.getLogger(__name__)

_AI_APPLY_CTX = "ai_apply_flow"
_AI_FB_CTX = "ai_feedback_worker"

# Human labels used when formatting corrections into AI prompts.
_FIELD_LABELS = {
    "premafirm_po": "PO #",
    "premafirm_bol": "BOL #",
    "premafirm_pod": "POD #",
    "load_reference": "Load reference",
    "client_order_ref": "Customer reference",
    "pickup_city": "Pickup city",
    "delivery_city": "Delivery city",
    "order_line_description": "order-line description",
    "price_unit": "unit price / rate",
    "product_id": "selected product",
    "ref": "invoice reference",
}


def _norm(value):
    """Stable normalization for hashing / equality."""
    return re.sub(r"\s+", " ", str(value or "")).strip().lower()


def _values_equal(ai_value, new_value):
    """Numeric-tolerant equality for AI-baseline vs edited values."""
    if ai_value is None and new_value in (None, "", False):
        return True
    if isinstance(ai_value, bool) or isinstance(new_value, bool):
        return bool(ai_value) == bool(new_value)
    try:
        if ai_value is not None and new_value not in (None, ""):
            return float(ai_value) == float(new_value)
    except (TypeError, ValueError):
        pass
    return _norm(ai_value) == _norm(new_value)


def _hash_pair(ai_value, user_value):
    return md5((_norm(ai_value) + "||" + _norm(user_value)).encode("utf-8")).hexdigest()


def _classify(ai_value, user_value):
    """Best-effort correction type based on text similarity.

    High overlap → the facts were kept and only the presentation changed
    (FORMAT). Medium overlap → wording/labels changed (LABEL). Low overlap or
    changed figures → the data itself was corrected (DATA).
    """
    ai_s, us_s = _norm(ai_value), _norm(user_value)
    if not ai_s or not us_s or ai_s == us_s:
        return "format_correction" if ai_s and us_s else "other"
    ratio = SequenceMatcher(None, ai_s, us_s).ratio()
    ai_toks = set(re.findall(r"[a-z0-9#%$.,:/-]+", ai_s))
    us_toks = set(re.findall(r"[a-z0-9#%$.,:/-]+", us_s))
    overlap = len(ai_toks & us_toks) / max(1, len(ai_toks))
    if ratio >= 0.85 or overlap >= 0.9:
        return "format_correction"
    if overlap >= 0.55 and ratio >= 0.45:
        return "label_correction"
    return "data_correction"


class PremafirmAiBaseline(models.Model):
    """One row per AI-generate target record: what the LAST AI run wrote."""

    _name = "premafirm.ai.baseline"
    _description = "AI Generate baseline snapshot (internal metadata)"
    _rec_name = "source_model"

    source_model = fields.Char("Source model", required=True)
    source_record_id = fields.Integer("Source record ID", required=True)
    source_ref = fields.Char("Source", compute="_compute_source_ref")
    partner_id = fields.Many2one("res.partner", string="Customer")
    snapshot = fields.Text("Snapshot (JSON)")
    generated_at = fields.Datetime("Generated at")
    created_by = fields.Many2one("res.users", string="Generated by")
    updated_at = fields.Datetime("Updated at")

    _sql_constraints = [
        ("uniq_source_record", "unique(source_model, source_record_id)",
         "A baseline snapshot already exists for this record."),
    ]

    @api.depends("source_model", "source_record_id")
    def _compute_source_ref(self):
        for rec in self:
            rec.source_ref = f"{rec.source_model} #{rec.source_record_id}"

    # ── helpers used by the quotation/invoice apply flows ────────────────
    def get_for(self, source_model, source_record_id):
        return self.search(
            [("source_model", "=", source_model),
             ("source_record_id", "=", source_record_id)], limit=1)

    def get_dict(self, source_model, source_record_id):
        """Baseline snapshot as dict (keys = field names / line:<id>:<field>)."""
        row = self.get_for(source_model, source_record_id)
        if not row or not row.snapshot:
            return {}
        try:
            payload = json.loads(row.snapshot)
            return payload if isinstance(payload, dict) else {}
        except (TypeError, ValueError):
            return {}

    def set_for(self, source_model, source_record_id, payload, partner=None,
                created_by=None, attachment_ids=None):
        """Create or replace the baseline row for one AI Generate run.

        The JSON snapshot carries the AI-written values plus internal metadata
        (source_attachment_ids of the documents the AI read). Internal
        metadata only — nothing is displayed in the quotation/invoice UI.
        """
        partner_id = partner.id if partner else False
        payload = dict(payload or {})
        if attachment_ids:
            payload["source_attachment_ids"] = sorted(set(attachment_ids))
        vals = {
            "source_model": source_model,
            "source_record_id": source_record_id,
            "partner_id": partner_id,
            "snapshot": json.dumps(payload, indent=2),
            "generated_at": fields.Datetime.now(),
            "updated_at": fields.Datetime.now(),
            "created_by": created_by.id if created_by else False,
        }
        row = self.get_for(source_model, source_record_id)
        if row:
            row.sudo().write(vals)
            return row
        return self.sudo().create(vals)


class PremafirmAiFeedback(models.Model):
    """One learned correction (deduplicated; repeats bump occurrence_count)."""

    _name = "premafirm.ai.feedback"
    _description = "AI Generate learned user corrections"
    _rec_name = "field_name"
    _order = "write_date desc, occurrence_count desc"

    source_model = fields.Char("Source model")
    source_record_id = fields.Integer("Source record ID")
    customer_id = fields.Many2one("res.partner", string="Customer")
    scope = fields.Selection([
        ("global", "Global"),
        ("customer", "Customer"),
        ("document", "Document/pattern"),
        ("field", "Field"),
    ], string="Scope", default="customer", required=True)
    field_name = fields.Char("Field", required=True)
    correction_type = fields.Selection([
        ("data_correction", "DATA correction"),
        ("format_correction", "FORMAT correction"),
        ("label_correction", "LABEL correction"),
        ("extraction_correction", "EXTRACTION correction"),
        ("ignore_field", "IGNORE field"),
        ("other", "Other"),
    ], string="Correction type", default="other", required=True)
    ai_value = fields.Text("AI-generated value")
    user_value = fields.Text("User-corrected value")
    source_document_type = fields.Char("Source document type")
    occurrence_count = fields.Integer("Occurrences", default=1)
    last_seen_at = fields.Datetime("Last seen")
    active = fields.Boolean(default=True)
    created_by = fields.Many2one("res.users", string="Recorded by")

    _sql_constraints = [
        ("uniq_correction_pattern",
         "unique(customer_key, scope, field_name, correction_type, "
         "source_document_type, ai_hash, user_hash)",
         "This correction pattern is already recorded — repeat occurrences "
         "increment occurrence_count instead of duplicating."),
    ]
    customer_key = fields.Char("Customer key", index=True)
    ai_hash = fields.Char("AI hash", index=True)
    user_hash = fields.Char("User hash", index=True)

    # ── human-edit gate ──────────────────────────────────────────────────
    @api.model
    def _human_session(self):
        """True only for interactive edits by an internal user.

        ai_force_human is honored for the automated E2E harness (which has no
        HTTP request context).
        """
        if self.env.context.get("ai_force_human"):
            return True
        if self.env.context.get(_AI_FB_CTX) or self.env.context.get(_AI_APPLY_CTX):
            return False
        from odoo import http
        if not getattr(http, "request", None):
            return False  # cron / script / shell / XML-RPC — never a UI edit
        user = self.env.user
        if user.share or getattr(user, "_is_public", lambda: False)():
            return False
        return True

    # ── recording ────────────────────────────────────────────────────────
    @api.model
    def record_correction(self, source_model, source_record_id, partner,
                          field_name, ai_value, user_value,
                          correction_type=None, source_document_type=""):
        """Deduplicate-or-create one correction row (always via sudo — the
        web user saving a record must never be blocked by feedback ACLs)."""
        if not self._human_session():
            return False
        ai_value = str(ai_value or "")
        user_value = str(user_value or "")
        if not ai_value or not user_value or _values_equal(ai_value, user_value):
            return False
        correction_type = correction_type or _classify(ai_value, user_value)
        commercial = partner.commercial_partner_id if partner else False
        customer = commercial or partner
        key_scope = "customer" if customer else "global"
        domain = [
            ("customer_key", "=", str(customer.id if customer else 0)),
            ("scope", "=", key_scope),
            ("field_name", "=", field_name),
            ("correction_type", "=", correction_type),
            ("source_document_type", "=", source_document_type or ""),
            ("ai_hash", "=", _hash_pair(ai_value, user_value)[:16]),
            ("user_hash", "=", _hash_pair(ai_value, user_value)[16:]),
        ]
        now = fields.Datetime.now()
        vals = {
            "source_model": source_model,
            "source_record_id": source_record_id,
            "customer_id": customer.id if customer else False,
            "customer_key": str(customer.id if customer else 0),
            "scope": key_scope,
            "field_name": field_name,
            "correction_type": correction_type,
            "ai_value": ai_value,
            "user_value": user_value,
            "source_document_type": source_document_type or "",
            "ai_hash": _hash_pair(ai_value, user_value)[:16],
            "user_hash": _hash_pair(ai_value, user_value)[16:],
            "created_by": self.env.user.id if self.env.user else False,
            "last_seen_at": now,
        }
        try:
            existing = self.sudo().search(domain, limit=1)
            if existing:
                existing.sudo().write({
                    "occurrence_count": existing.occurrence_count + 1,
                    "last_seen_at": now,
                    "active": True,
                })
                return existing
            return self.sudo().create(vals)
        except Exception:
            _logger.exception("Failed to store AI feedback (%s %s)", source_model,
                              source_record_id)
            return False

    # ── retrieval for prompts ────────────────────────────────────────────
    def retrieve_for_prompt(self, partner, limit=8):
        """Small, relevant set of learned corrections formatted for the prompt.

        Eligibility is strict: only corrections for the SAME commercial
        customer and GLOBAL rows (no customer, scope 'global') are ever
        returned, so one customer's corrections can never leak into another
        customer's prompt.  Same customer ranks first, global second; within
        a tier most frequent first (write_date desc breaks ties).  If fewer
        than `limit` eligible rows exist, fewer rows are returned — the
        remaining slots are never filled with another customer's feedback.
        Never dumps the whole table.
        """
        rows = self.sudo().search([("active", "=", True)], order="write_date desc")
        if not rows:
            return ""
        customer = partner and (partner.commercial_partner_id or partner)

        def _tier(row):
            """0 = same commercial customer · 1 = global · None = ineligible."""
            if row.customer_id and customer and row.customer_id.id == customer.id:
                return 0
            if not row.customer_id and row.scope == "global":
                return 1
            return None  # another customer's correction — never shown

        eligible = [row for row in rows if _tier(row) is not None]
        rows = sorted(eligible, key=lambda r: (_tier(r), -r.occurrence_count))
        rows = rows[:limit]
        lines = []
        for row in rows:
            label = _FIELD_LABELS.get(row.field_name, row.field_name)
            who = "the customer" if row.customer_id else "global"
            if row.correction_type == "format_correction" and \
                    row.field_name == "order_line_description":
                lines.append(
                    f"Description layout preference ({who}, used "
                    f"{row.occurrence_count}×):\n{row.user_value[:900]}")
            elif row.correction_type == "ignore_field":
                continue
            elif row.correction_type in ("data_correction", "extraction_correction"):
                lines.append(
                    f"On {label} ({who}, {row.occurrence_count}×) the AI value "
                    f"'{row.ai_value[:120]}' was corrected to '{row.user_value[:120]}' "
                    f"— prefer the corrected value when the document allows it.")
            else:  # label / format on other fields
                lines.append(
                    f"On {label} ({who}, {row.occurrence_count}×) the AI wrote "
                    f"'{row.ai_value[:120]}' and the user prefers "
                    f"'{row.user_value[:120]}'.")
        if not lines:
            return ""
        return ("══ PREVIOUS USER CORRECTIONS (learned) ══\n"
                "These reflect real manual corrections staff made after earlier "
                "AI Generate runs. Respect them — prefer the corrected value/"
                "layout whenever the current document allows it:\n"
                + "\n\n".join(lines))


# ════════════════════════════════════════════════════════════════════════
# Write hooks: detect human edits of AI-generated values AFTER the fact.
#
# Every hook only reacts to the CURRENT write (the lines in `self` and the
# fields present in `vals`) — never to the whole record — so ordinary later
# saves (confirm, tax recompute, chatter, unrelated fields) cannot re-record
# or re-increment a correction. All hooks are exception-safe and early-exit
# when there is no baseline or no interactive human session, so they can
# never break a normal save.
# ════════════════════════════════════════════════════════════════════════
_BASELINE_MODELS = ("sale.order", "account.move")


def _human_env_ok(env):
    """Interactive human write, outside the AI apply flow itself."""
    if not env or env.context.get(_AI_APPLY_CTX) or env.context.get(_AI_FB_CTX):
        return False
    return env["premafirm.ai.feedback"]._human_session()


def _record_header_if_changed(record, field, ai_value):
    current = getattr(record, field, None)
    if _values_equal(ai_value, current):
        return
    partner = record.partner_id if hasattr(record, "partner_id") else False
    record.env["premafirm.ai.feedback"].record_correction(
        record._name, record.id, partner, field, ai_value, current)


def _product_choice_label(env, value):
    """Baseline product choice (stored as the product id) → the product's
    display name, so prompts read 'selected product: X → Y', never raw ids.
    An unknown/archived id keeps a readable 'product <id>' anchor."""
    try:
        if isinstance(value, models.BaseModel):
            product_id = value.id
        else:
            product_id = int(value)
    except (TypeError, ValueError):
        return str(value or "").strip()
    product = env["product.product"].sudo().browse(product_id).exists()
    if not product:
        return f"product {product_id}"
    return (product.display_name or product.name or "").strip() \
        or f"product {product_id}"


def _record_line_if_changed(line, field, ai_value, partner):
    current = getattr(line, field, None)
    if field == "product_id":
        # A human re-picking the product on the line (choice correction).
        ai_value = _product_choice_label(line.env, ai_value)
        current = _product_choice_label(line.env, current)
        if _values_equal(ai_value, current):
            return
        line.env["premafirm.ai.feedback"].record_correction(
            line._name, line.id, partner, "product_id", ai_value, current)
        return
    if _values_equal(ai_value, current):
        return
    if field == "name":
        # Re-picking a product auto-defaults the line label; that is not a
        # human correction of the AI description.
        if not current:
            return
        prod = line.product_id
        if prod and _norm(current) in (_norm(prod.name), _norm(prod.display_name)):
            return
    fb_field = "order_line_description" if field == "name" else field
    line.env["premafirm.ai.feedback"].record_correction(
        line._name, line.id, partner, fb_field, ai_value, current)


def _baseline_line_entries(payload):
    """[(line_id, field, ai_value)] built from 'line:<id>:<field>' keys."""
    entries = []
    for key, ai_value in payload.items():
        if not key.startswith("line:"):
            continue
        parts = key.split(":")
        if len(parts) == 3 and parts[1].isdigit():
            entries.append((int(parts[1]), parts[2], ai_value))
    return entries


def _detect_header_edits(records, vals, model_name):
    """Learn human edits of AI-generated HEADER values of this record."""
    if not records or not _human_env_ok(records.env) or \
            model_name not in _BASELINE_MODELS:
        return
    baseline = records.env["premafirm.ai.baseline"]
    for rec in records:
        payload = baseline.get_dict(model_name, rec.id)
        if not payload:
            continue
        for key, ai_value in payload.items():
            if key.startswith("line:") or key not in vals:
                continue  # only fields touched by THIS write
            if not hasattr(rec, key):
                continue  # internal metadata keys inside the snapshot
            _record_header_if_changed(rec, key, ai_value)


def _detect_line_edits(lines, vals, parent_model, parent_attr):
    """Learn human edits made directly on order/move LINE records."""
    if not lines or not _human_env_ok(lines.env):
        return
    baseline = lines.env["premafirm.ai.baseline"]
    parents = {}
    for line in lines:
        parent = getattr(line, parent_attr, None)
        if parent:
            parents[parent.id] = parent
    index = {}
    for parent in parents.values():
        payload = baseline.get_dict(parent_model, parent.id)
        if not payload:
            continue
        partner = parent.partner_id if hasattr(parent, "partner_id") else False
        for line_id, field, ai_value in _baseline_line_entries(payload):
            index[(line_id, field)] = (ai_value, partner)
    for line in lines:
        for field in vals:
            hit = index.get((line.id, field))
            if hit:
                ai_value, partner = hit
                _record_line_if_changed(line, field, ai_value, partner)


class SaleOrder(models.Model):
    _inherit = "sale.order"

    def write(self, vals):
        res = super().write(vals)
        try:
            _detect_header_edits(self, vals, "sale.order")
        except Exception:
            _logger.exception("AI feedback detection failed on %s", self.ids)
        return res


class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    def write(self, vals):
        res = super().write(vals)
        try:
            _detect_line_edits(self, vals, "sale.order", "order_id")
        except Exception:
            _logger.exception("AI feedback detection failed on lines %s", self.ids)
        return res


class AccountMove(models.Model):
    _inherit = "account.move"

    def write(self, vals):
        res = super().write(vals)
        try:
            _detect_header_edits(self, vals, "account.move")
        except Exception:
            _logger.exception("AI feedback detection failed on move %s", self.ids)
        return res


class AccountMoveLine(models.Model):
    _inherit = "account.move.line"

    def write(self, vals):
        res = super().write(vals)
        try:
            _detect_line_edits(self, vals, "account.move", "move_id")
        except Exception:
            _logger.exception("AI feedback detection failed on move lines %s",
                              self.ids)
        return res
