"""PHASE 9 — AI provenance on the canonical outbound record.

Every ``mail.mail`` created by an AI path is stamped so the audit trail
distinguishes:

* AI Draft        — ``generated_by_ai``, no ``approved_by`` yet
* AI Approved     — ``generated_by_ai`` + ``approved_by`` + ``approved_at``
                    (human reviewed and approved the AI draft)
* Auto-Sent       — ``generated_by_ai`` + ``auto_sent`` (campaign /
                    follow-up service, no human approval — PHASE 15)
* Human mail      — none of the flags (untouched)

"One action = one canonical outbound email record": AI paths build ONE
``mail.mail`` through ``premafirm.mail.threading.build_mail_values``; the
attached ``mail.message`` (``mail_message_id``) IS the same email — no
separate "comment" post, no second mail, and the mail is attached to the
existing opportunity (``model='crm.lead'`` + ``res_id``), so nothing can
accidentally create another lead.
"""
from odoo import fields, models


class MailMail(models.Model):
    _inherit = 'mail.mail'

    generated_by_ai = fields.Boolean(
        'Generated by AI', index=True,
        help='This outbound email was drafted by the AI assistant.',
    )
    approved_by = fields.Many2one(
        'res.users', 'Approved By', index=True, ondelete='set null',
        help='Human who reviewed and approved the AI draft.',
    )
    approved_at = fields.Datetime(
        'Approved At', index=True,
        help='When the human approved the AI draft for sending.',
    )
    auto_sent = fields.Boolean(
        'Auto-Sent', index=True,
        help='Sent without human approval (campaign / follow-up service).',
    )
    ai_prompt_version = fields.Char(
        'AI Prompt Version',
        help='Prompt/profile version that produced the draft.',
    )
    idempotency_key = fields.Char(
        'Idempotency Key', index=True,
        help='PHASE 10 — unique key of the bulk-send attempt that created '
             'this mail; a crashed queue item can never resend the same '
             'mail (the key travels on the record).',
    )

    def _stamp_ai_provenance(self, *, auto=False, prompt_version=False):
        """Stamp AI provenance on this mail.mail (approve-send path)."""
        self.ensure_one()
        self.write({
            'generated_by_ai': True,
            'approved_by': self.env.user.id if not auto else False,
            'approved_at': fields.Datetime.now() if not auto else False,
            'auto_sent': auto,
            'ai_prompt_version': prompt_version or False,
        })
        return self
